#!/bin/sh

alias r="riverctl"
alias m="riverctl map"

. "$HOME/.config/river/scale"
# pad=$((scale * 8))

r set-repeat 60 350

m normal Super Return  spawn foot
m normal Super C       close

m normal Super J       focus-view next
m normal Super K       focus-view previous
m normal Super+Shift J swap next
m normal Super+Shift K swap previous

m normal Super W       zoom

# r default-layout rivertile
# rivertile -view-padding $pad -outer-padding $pad &
# foot --server &
