ssh-discord-webhook-url: ENC[AES256_GCM,data:LZdNOPZ4WJ1s+egLBdUGCrNt2reOZ0eKcQVC4PGnx2zeitphT07hQVoTlCpN4STmsodTZqGT75172+JZICPGA+sJEXStz+6W9Qk3shw6EU7SMlsi/H7AK8i1P8CqdPJmB0uHJcm38SfHKh2B/cRqFS/MKR/J+TfcPQ==,iv:TXsnx11AQh+RSbrmt8v8+V4gOdXuf1dG5JXogngjC08=,tag:ra4Rj1QSs5c20GCtR/XrpA==,type:str]
sops:
    age:
        - recipient: age140kzyrzxdj062846re2ez345z7u6ld6gwhvydyavfznsphynqcxqqpq9lr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb2IwaXFOcjBQK0xFZXYw
            UXBUYU5qeFVWaFRTc003WW9WZHZRaS9MaFNBClBtT28zWEt5WWFRT0NjUjIwMlc1
            bzlhUGZmOWNkQ0xwUkRBZlg2VU5wRmsKLS0tIGVHcWdsTk5hdHRUbGppcU9ETHFE
            R09qMDN0cmRrcjk4cGxza2xQYXpUSUUKbDXDY+tFb4g1STDpcQbUT7N8pd0ldff/
            0oyh7HyJl48/3xjKLJ4vmdzIexEhobNJD+SuWdak4SRLDn3INYCatw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uwnwqs5gcdkzhuuc36r3t6s2f3ct7l6hpuxtk80xnlhxp6vx7g2qkxgacy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT2FhaHZIL1RkeThlckZu
            TnE3K2dralJZR1BheVZ5ZUtrQVUyTG9va2lBCkFrb3c5blg5R1dibit4aFpHTzZh
            cEhFVXlsMGUreFJrQXRzQmxlRXZPWWsKLS0tIGdqa3phTmI4L2NOOUp3MDEwMno5
            OGVvRXcwUzlJQmZ6SUd1cmlaY2RsNk0KxSJV6y0TDwUyGNA34S86+3bqa+/C3J7Z
            ibcnpRwLXrvuLOtr4aga0Ygz/blkNyerp9kyE3yKI6LXDmUsqAKw4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nadt5x4v99usntanplxcmr2rftqkzlh9cd7saffr9ea9zuf9zuxqk0zd7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQ0ticDhsVVRCTG9lSGlS
            dDNzT1VCdHB3a3NRZmxKSjZHRC90aUVnaW1nCnNDeGFQcUc3YWh3TklnV1YyNjRu
            MzBhck94SnFNVk0rZGNFRElROTIvNm8KLS0tIEhPRTIxWnZ5UE5TZlY2a3ZqWDRW
            blE3YStLY0FEQzI3M1J5Q0ttTFpMS1EK8plT/QRIMYgef7wfF+UFlc9CTckR25aH
            jxGs430PUsYj3DSVp8A1opfKVfX8QTH9O2VKJr1Dfc2BZZRWW9iiOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T05:33:38Z"
    mac: ENC[AES256_GCM,data:YZIYjMRiMy4+RWtlD9Ee5VWfN4CVMZmMQ2xqvnW2XVHDjhtCmntwlvZdCuXk1wftm/Hd7DRc7qMs3Eo2iLbXX7OEmLaciq7AXLgbYTfxJreBdH/pAcSg003UA1PtzDUDS9kdUqkMgfzQ8forqerLfckrkLzCWJclMOTTyx9ZexE=,iv:7jChCNgKJrBMdb9WKMGRw/MV06WPtYehonSY9YyakWc=,tag:29f61OiYzroOqysDEy/8iw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
