ssh-discord-webhook-url: ENC[AES256_GCM,data:LZdNOPZ4WJ1s+egLBdUGCrNt2reOZ0eKcQVC4PGnx2zeitphT07hQVoTlCpN4STmsodTZqGT75172+JZICPGA+sJEXStz+6W9Qk3shw6EU7SMlsi/H7AK8i1P8CqdPJmB0uHJcm38SfHKh2B/cRqFS/MKR/J+TfcPQ==,iv:TXsnx11AQh+RSbrmt8v8+V4gOdXuf1dG5JXogngjC08=,tag:ra4Rj1QSs5c20GCtR/XrpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uwnwqs5gcdkzhuuc36r3t6s2f3ct7l6hpuxtk80xnlhxp6vx7g2qkxgacy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnZ6MVROUzZQSVd6TlZv
            dWdoamdJeEJMam1XTUNLSm9qeE1oNVhXdDA0CnNnUDVkbEpOQTlNdWdhUmZhd0lR
            SC8weWZzR1Vjdk1zVkQ0bE5hVWtZQlEKLS0tIG5naGhTTGdhZW12dlVjekRhakJS
            QXdnM2xWODFGMkNDUTNwdEFxRWhkV1UKqMX3mD5bDGB/I1rBafLj2i4n4KwsLd6C
            0FQYzKu/digvbjEKkE7CstlaP0GqgBw8gCOmzXbc2GXW1X0QhLeOkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nadt5x4v99usntanplxcmr2rftqkzlh9cd7saffr9ea9zuf9zuxqk0zd7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNVpNaFQxVnoxWk1GbU1K
            NEE2NzNwaGVMTWxpQlg5bmkwTGRoNDEyOFMwCm5FTkhDeU9aVzBMdGZmRU9rU3pV
            amR2OUtwK0hKUUJLejAwS1IwbGZQVVEKLS0tIDZnN0RZM0xNVUJlVTE4WkhUUkh0
            Q3Z6MkI1enJiQVRMcGJ5aG9OK1E5OVEKviv+UpwCch8uvBhPa6+ExTHKVIcwXLHY
            a3ZeanKdYuK93oUe1czVj45yMBR3ocdD/9+q+8EBcqQpO6gCsvbw6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-10T05:33:38Z"
    mac: ENC[AES256_GCM,data:YZIYjMRiMy4+RWtlD9Ee5VWfN4CVMZmMQ2xqvnW2XVHDjhtCmntwlvZdCuXk1wftm/Hd7DRc7qMs3Eo2iLbXX7OEmLaciq7AXLgbYTfxJreBdH/pAcSg003UA1PtzDUDS9kdUqkMgfzQ8forqerLfckrkLzCWJclMOTTyx9ZexE=,iv:7jChCNgKJrBMdb9WKMGRw/MV06WPtYehonSY9YyakWc=,tag:29f61OiYzroOqysDEy/8iw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
