fake-domains-hosts-file: ENC[AES256_GCM,data:eVN3cCyO8kLj9hVnGq/EMfFLoHpxys6ufbHg2HZv55EzZ6GtR5Cx82v3d+aqJWbTtYqzhtkPC4xXEDyEh4Gtx3SnI6nkrEhwuYnirtultx+FCuYXcO+eeHmTYA74ds7nazdO0PZADTP/yb5BD/gz,iv:48vL7YZ7Cdw2hJ72eAXPl6y1FggSpbWvjTClFCzwQBw=,tag:rm8VfXr/n5GvQRUEYaxQiw==,type:str]
sops:
    age:
        - recipient: age140kzyrzxdj062846re2ez345z7u6ld6gwhvydyavfznsphynqcxqqpq9lr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRHlrYUlOQTd3RjkrbjZJ
            aEdKbDdsNytqSWdzRjhySElMTjJINGk4TUNBCjI4REk5RmJ6eng5TmgrT05ndkhD
            Q0tGUk1SSDNMMGdnTFV6ZW4wQ0kwZ0UKLS0tIEF0K0l4NkdPZWF0RWp2WkdKTndZ
            Yk5saEVhdHprelIwWG9QNk5vR29sbXMKHuTyAOZhQyfzeO7YifHB6YqEgWm3JTX0
            2yFYMO8w87ihNkIaIpJiv3hnlnODF8EuaNwxjTJ55Wqyvq7GfcjQdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uwnwqs5gcdkzhuuc36r3t6s2f3ct7l6hpuxtk80xnlhxp6vx7g2qkxgacy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dmxMcjBYbEdYTyszb2ZC
            M2YyY0Q1VVkrL0xwZkNMbCtDNExNczVJUFQ4CmM2bjJ0cnNITGd0bFowQU5raDVt
            a2N0dFczcm90WFNZN21NYmpTSmlWN0EKLS0tIGZjR1BaYnBDdEorTDMwSzFxTDd1
            L2R5dzJITC9VT0srYnRESlV4OWgrdFkKbRyx6L087/aLcWvCnR0/fKornPYbsqCl
            bqy0D6MhcV462pt2msrBUXPoAwUUKvzo2rO4Kg+747DpTdaXsMFgbg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nadt5x4v99usntanplxcmr2rftqkzlh9cd7saffr9ea9zuf9zuxqk0zd7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dWxzV3lJQjV3Rmo3YTNE
            WWJlMFRHOUxMMzJibW8rblRpdXFnbTh1M2pnCnEzOG9pUG5SOExyRTFmWDNPVFZ4
            Mnd0ZHFCMmd4eUJ6NFhlM09GYzlVQXcKLS0tIG9nUWN3WWJ5YVlaanp1SkdRSEFG
            VzFIbnluMjlKbmp4WE90S1haMjN6ZUkKFTAOO3aCgpbnEymWO9wFZEmjyN67LAMC
            07xi7CesOuBMtA+ruzfCEj/YP/6s9pVthuTQCBtNBj31ZDlTSg0uqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T01:32:27Z"
    mac: ENC[AES256_GCM,data:3f7LeUiMm/DL62ySClK4Pu5cgVqfcsMn8GrREX5YuDEwwgWlc7FFz9uwWvX4sj7SiUIDq0gv6euOsqSFBa6EcESDA3A7i6PFj28Muv3c1cHuGvr2mfJdAUHGoxucCxZgzNAPkUJcm8accYqT3m4+ofxqotRYU0qebFc+Hn6G9TI=,iv:Po+RzVPPfZSey9dpDzpKQR/PX5KeXoSCX79gv/RgSeg=,tag:MxcC3BR/SJ9TOX/LGKT9GA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.1
