fake-domains-hosts-file: ENC[AES256_GCM,data:eVN3cCyO8kLj9hVnGq/EMfFLoHpxys6ufbHg2HZv55EzZ6GtR5Cx82v3d+aqJWbTtYqzhtkPC4xXEDyEh4Gtx3SnI6nkrEhwuYnirtultx+FCuYXcO+eeHmTYA74ds7nazdO0PZADTP/yb5BD/gz,iv:48vL7YZ7Cdw2hJ72eAXPl6y1FggSpbWvjTClFCzwQBw=,tag:rm8VfXr/n5GvQRUEYaxQiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uwnwqs5gcdkzhuuc36r3t6s2f3ct7l6hpuxtk80xnlhxp6vx7g2qkxgacy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU24yVUNIOU9wODFmUkhy
            ZktRajA5YVI4VGF0SEUrckhSYnBubnBOd0hVClVxS3hhUFRtZ1h5OG9aeVByVVFw
            Z2xvakZvK2tHYjJLV2l5MzM1VWRhSGcKLS0tIERNQlROMi90dDdhTitwOUpqQnQy
            RGdGQ0ZnRVdJNW5LZHYwZ1VoZXNMVE0K8IW33fBfBybLq7yT/o0BoFWU1YfxPwlZ
            zXD3K3JF2DUUPrcd4MvqxSSHA5aK5BTUq/8B9WBz7ZNptL1ZFL0LZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nadt5x4v99usntanplxcmr2rftqkzlh9cd7saffr9ea9zuf9zuxqk0zd7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QXNzLytOa1owR3RCZENI
            WHk4ekF6OE1tU0ZqSW9Fbm5uaGtYcnRKb3o4CmV0SFZwbmwydlZMTVFFVHNQOUFQ
            WWVhNDFRcVZRdjlFWXdaVjAxS3RvcFkKLS0tIHJtSGNVTEt5bm1jY0MzenkvR2lB
            anBlM2w4QWJyWUNtNEpPM1hzN3A2MmMKnFM/GoEB8/BYt/7u8lkdHlX6wXni0j8P
            TSnobl4saCoHCbIK/u4h32ktjDjs/n7ZhaE0Tson/WdVeVNyZWlFGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T01:32:27Z"
    mac: ENC[AES256_GCM,data:3f7LeUiMm/DL62ySClK4Pu5cgVqfcsMn8GrREX5YuDEwwgWlc7FFz9uwWvX4sj7SiUIDq0gv6euOsqSFBa6EcESDA3A7i6PFj28Muv3c1cHuGvr2mfJdAUHGoxucCxZgzNAPkUJcm8accYqT3m4+ofxqotRYU0qebFc+Hn6G9TI=,iv:Po+RzVPPfZSey9dpDzpKQR/PX5KeXoSCX79gv/RgSeg=,tag:MxcC3BR/SJ9TOX/LGKT9GA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
