cloudflare-acme-tokens: ENC[AES256_GCM,data:YGI2zogwYYkKSZUQIYIY8bG+iClt27oFKghlZJ6k8bZQ6psXK8R1lkumQ7ThBRaCDQBRJA2jSfZYUQ0NK9fDNS3BjxPAVgqOBy9YpOboZNEbkZ18ALTxBfnceY39sBKE5ZgdmBr3iAAVEolVZ3Z9p8TaXDwb,iv:2BhQE0mnOm5WXRUz7b7k+FrClw1DQoyVvpDVLH3lkM0=,tag:Q/QukeBve8Iw3SzYgQ0jzg==,type:str]
sops:
    age:
        - recipient: age140kzyrzxdj062846re2ez345z7u6ld6gwhvydyavfznsphynqcxqqpq9lr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS3U2cFNWelk5V3NjMmVN
            bXZESGJoNkFKTnFVZXZBeVdNRlNVTFg1ZVFBCnNNUHhNL2kzR0prYjZQc0lkb3Vq
            QTc5anFCdjRjMGNYM1RjMGdGcUY5RjgKLS0tIHpRc25rZjk2bVhMd0lHNmUwSWpE
            c0tNbGNaUXlZK2EvZWRrQzdxbDlyR3MKySnz3Sf90VgoF60CG006cD3x64ExT2hi
            TT7Kh4qoAL5KZMUUklQS/mZ0uXSevdKWebed9Ma7Wca2Y95KxYGJ/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uwnwqs5gcdkzhuuc36r3t6s2f3ct7l6hpuxtk80xnlhxp6vx7g2qkxgacy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERUpFeHdJQUFuOFZmQzJE
            R3kvbXRoWUxJQm14d0N0c3BoUmRvVHdCSldRClEyZC9uS3lLSldJVFN5MVBGSHlD
            MTBqZVRjNlJ0RjMrZng0ZGIzVU95UHcKLS0tIHN5aGw2Q24vd1lGMzJ4TWl2S3Yy
            OHNWSXF3eXBGRSthMUptSDFVaUpDYzAK07X2Zm4XbPN68slGTcXN0BSCow0Tcv4T
            Uf+ySSvGs/euPj8C4iD2b5GDgYmXGGMYv6hYbuMkLMRgkZzWx2WHwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nadt5x4v99usntanplxcmr2rftqkzlh9cd7saffr9ea9zuf9zuxqk0zd7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WVo3cmJpTTRxUFpwNk5F
            YmVVTUE2TE0yK29zKzQ4YnB3NkV4SGh4U2lvCkpob1lZc3c1QVN3RllXQThXQkxT
            ZkZLOWFDNkRlRjRUaGRFNFdBRDJvT2cKLS0tIERmS1laejByK1lGdE0zWGNpL0Qv
            YkNlWS94R3Fid0huZUxDZzgzem11OUkKcTnI68mZFP+kdu82u7PMVv+jsAw3KVjd
            3ss0ZAOnJ1JCEYOGV6iluthIvsRFCA5RAmNswlLGz0mYQNKii1aDhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T00:31:19Z"
    mac: ENC[AES256_GCM,data:+xhpIhreeb3/yj+Lte0MxH5lj8LNlXPr6Qzjbk7vAExUPxhNq6DeYp/LTaiMj9PGLdbmwujZvYIwZNTSi9AFtAyJwEwdNEWv6MA+phMsoeN1wz/C58q3l193ihMNHZL5AM0R4WQFj8ogJbT4JrrPm2n4OBrn4r+tVC74Uo5iVRE=,iv:GuvdHkYuGtt0fTR4RXtMJnM35bYoC2jyimdv6Jeh/J0=,tag:27hkygIIg3PVpPIcAvIVmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
