cloudflare-acme-tokens: ENC[AES256_GCM,data:YGI2zogwYYkKSZUQIYIY8bG+iClt27oFKghlZJ6k8bZQ6psXK8R1lkumQ7ThBRaCDQBRJA2jSfZYUQ0NK9fDNS3BjxPAVgqOBy9YpOboZNEbkZ18ALTxBfnceY39sBKE5ZgdmBr3iAAVEolVZ3Z9p8TaXDwb,iv:2BhQE0mnOm5WXRUz7b7k+FrClw1DQoyVvpDVLH3lkM0=,tag:Q/QukeBve8Iw3SzYgQ0jzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uwnwqs5gcdkzhuuc36r3t6s2f3ct7l6hpuxtk80xnlhxp6vx7g2qkxgacy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbGNRWlV2a1hlSmw3ZFBp
            R0kyVTh2WmM2UTRRVnIwQUlqRUcrdm8yZWw4CmRQcUxsVnFIMStTeVhCbXcwU0Ft
            VlJFZFY5Uk5uOG1EQndJUUM2d0tFaEUKLS0tIDhMdW9QYnRydE1FM21XQ2NWZHp2
            YkFNZ2JtcllnRzA1blJoLzN3NkNjcEkKurK0rQVbwPPDl+fhfj+wqEN6vw7OfRtl
            WWapw265ZakUPmmBtEDbpHaZ0Gbt8Q81nk5x6pLlbLqdVd8Yk65nlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nadt5x4v99usntanplxcmr2rftqkzlh9cd7saffr9ea9zuf9zuxqk0zd7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQW94MUtSNC9wbXJOZkIy
            Q0JlVnpHbG1CdHhHUkk0SVVNZXRkeHk3VW1nCkY2ZzJKNVR4Z0I1bWhVRmNWa0Jr
            UjlURWVLNEQ0SWNhUW0rTlRLV3VkSFUKLS0tIFk1SWN1bVg0a25DR1Jwc3BtSU9L
            KzBaaUY5Q3JQbmJlMWZkV1RYS0lxN28KJD1EvrfEswLZ3yfeh7pcx7P9q0X+Zdx3
            wgr5kF0LlVOCQcB8kqlS9EFrxGJkkf8WMcNoj2HA6F1eMrM5ZjK0Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T00:31:19Z"
    mac: ENC[AES256_GCM,data:+xhpIhreeb3/yj+Lte0MxH5lj8LNlXPr6Qzjbk7vAExUPxhNq6DeYp/LTaiMj9PGLdbmwujZvYIwZNTSi9AFtAyJwEwdNEWv6MA+phMsoeN1wz/C58q3l193ihMNHZL5AM0R4WQFj8ogJbT4JrrPm2n4OBrn4r+tVC74Uo5iVRE=,iv:GuvdHkYuGtt0fTR4RXtMJnM35bYoC2jyimdv6Jeh/J0=,tag:27hkygIIg3PVpPIcAvIVmA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
