[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants.design]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "upright-arched-serifless"
six = "straight-bar"
seven = "straight-serifless"
eight = "two-circles"
nine = "straight-bar"
zero = "slashed"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "straight-serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-w = "straight-serifless"
capital-z = "straight-serifless"
g = "single-storey-serifless"
u = "toothed-serifless"
y = "straight-serifless"
capital-eszet = "flat-top-serifless"
long-s = "bent-hook-serifless"
lower-eth = "straight-bar"
lower-delta = "flat-top"
lower-iota = "zshaped"
lower-mu = "toothed-serifless"
lower-pi = "tailed"
lower-tau = "short-tailed"
lower-phi = "cursive"
lower-chi = "semi-chancery-curly-serifless"
lower-psi = "flat-top-serifless"
cyrl-capital-zhe = "symmetric-connected"
cyrl-capital-ze = "serifless"
braille-dot = "round"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "threefold"
dollar = "open"
cent = "open-cap"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "corner"
pilcrow = "low"
partial-derivative = "straight-bar"
micro-sign = "toothed-serifless"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaCustomManuscript]
family = "Iosevka Custom Manuscript"
spacing = "term"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCustomManuscript.variants]
  inherits = "ss20"

    [buildPlans.IosevkaCustomManuscript.variants.design]
    one = "base"
    two = "curly-neck-serifed"
    three = "flat-top-serifed"
    four = "semi-open-serifed"
    five = "upright-arched-serifed"
    six = "closed-contour"
    seven = "bend-serifed-crossbar"
    eight = "two-circles"
    nine = "closed-contour"
    zero = "slashed"
    capital-i = "short-serifed"
    capital-j = "serifed-both-sides"
    capital-k = "curly-serifed"
    capital-m = "flat-bottom-serifed"
    capital-n = "standard-serifed"
    capital-p = "closed-serifed"
    capital-q = "curly-tailed"
    capital-r = "standing-serifed"
    capital-t = "serifed"
    capital-u = "tailed-serifed"
    capital-w = "curly-serifed"
    capital-x = "curly-serifed"
    capital-z = "curly-serifed"
    g = "double-storey-open"
    i = "tailed-serifed"
    j = "serifed"
    m = "serifed"
    n = "straight-serifed"
    q = "straight-serifed"
    t = "bent-hook"
    u = "tailed-serifed"
    x = "semi-chancery-straight-serifed"
    y = "cursive-serifed"
    capital-eszet = "flat-top-serifed"
    long-s = "bent-hook-bottom-serifed"
    lower-eth = "curly-bar"
    lower-delta = "flat-top"
    lower-iota = "tailed-serifed"
    capital-lambda = "straight-tri-serifed"
    lower-lambda = "tailed-turn"
    lower-mu = "toothed-serifless"
    lower-pi = "tailed"
    lower-tau = "tailed"
    lower-phi = "cursive"
    lower-chi = "semi-chancery-curly-serifed"
    lower-psi = "flat-top-serifed"
    cyrl-capital-zhe = "symmetric-connected"
    cyrl-capital-ze = "unilateral-serifed"
    braille-dot = "round"
    asterisk = "penta-low"
    underscore = "above-baseline"
    caret = "medium"
    ascii-grave = "straight"
    ascii-single-quote = "straight"
    paren = "normal"
    brace = "straight"
    number-sign = "upright"
    ampersand = "et-toothed"
    at = "threefold"
    dollar = "open"
    cent = "open-cap"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"
    pilcrow = "low"
    partial-derivative = "straight-bar"
    micro-sign = "toothed-serifless"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-plus-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"
