lastfm-pw: ENC[AES256_GCM,data:bfHp3eoVUIH7HX4=,iv:D6dCp6Q1dJQDDgMXZ0dgZFE24e4fSLHoe2JlVSjEQzU=,tag:7clL6SnvUZeqCNpZ6j7fog==,type:str]
sops:
    age:
        - recipient: age140kzyrzxdj062846re2ez345z7u6ld6gwhvydyavfznsphynqcxqqpq9lr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzME9kemxvQitOYlhDVW1i
            d3RoeC96VjBjWC9DN3R4Q0IxaWlSTktreGh3CjE4RFk4UmxtRWpPOU5MKy9iNzV1
            REIxdk5VeGluSWVIdEYxTlZiTlgyWUkKLS0tIGwybUN6bHlWd0RieWlFd1JjMFNU
            WnUyR3pRc09OdmFVM0NuRlg2SnNnc3cKb+0tdUFU8qovgXpb8XLVoXuzImTZRoYH
            NXtBvqr+ND8M/gYwYZ+Gyx6xtJcMY8xpN4FJyw99ggFtSkM33hyrsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uwnwqs5gcdkzhuuc36r3t6s2f3ct7l6hpuxtk80xnlhxp6vx7g2qkxgacy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMExZaTdaMUgyY3g0MzNp
            RnA1c3N2SlFNUUxNamlRTmpWbzhlcUFqZlc4Cmp5R1ZnT2VvYlVFelVVMmVZTmpV
            aUh2b0xuNlIvR0ttY2RzWnJSYjkxUzAKLS0tIHZLZkJGd21qeEsxVmVxRjFRZHFX
            MThRYWxGa1VOUXhURlpuNFVEcHppS2MK79aqUYs9df3k66F9crGprSIZSJ39E9N2
            BMVij6/lCjMWb8LoWekjAPCGcf1o3VJXO4Pg9wMiw8JIvng74VhsiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nadt5x4v99usntanplxcmr2rftqkzlh9cd7saffr9ea9zuf9zuxqk0zd7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNktZR0Jld1VMRkpVeDNu
            c2ZLc3RhNk1BbnlUSHZ4RkFSMi9wekx6QUJnCjhjK2JOeHJ2YjJqaHJhbnBRblhG
            YjdVZ2ZoNTdLZXkrclU0aTdnNW9UV0EKLS0tIGdhMHlRaEoxVWJlZXliMml2S3l2
            aXdpbnRDcW9VN1pPemh6cnoxTTVQbkEKv8K0at9QO7tpdQCK4zHd+dd0eRSZe9s7
            iH9zN3dx+E/q8pMK6ykEFhVkNGXa1MsFggmFXuDuf5Pwyk3sKuy30w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T01:31:44Z"
    mac: ENC[AES256_GCM,data:XtUtuAB9r1QBzOE9C/08CIllrbi5XcB+svqleXe80eWkWPKXMLVATrR7jcHlUZefdT3yYa/eavQ8JORjMj4JwX8s3jQ8ofQPW/urUvtMQM6qCyi836igpXtL0BQm3EES8FyS3LV4ScWGx0QalLwNHafko1ei0XEs1ATSMkvahJ4=,iv:S2/oIx100eJcwQFk5klw9gLyemItfHPNDWHPaZWDIL8=,tag:ucXY+2KX4URYxXwXtlMyBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.1
