lastfm-pw: ENC[AES256_GCM,data:bfHp3eoVUIH7HX4=,iv:D6dCp6Q1dJQDDgMXZ0dgZFE24e4fSLHoe2JlVSjEQzU=,tag:7clL6SnvUZeqCNpZ6j7fog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uwnwqs5gcdkzhuuc36r3t6s2f3ct7l6hpuxtk80xnlhxp6vx7g2qkxgacy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNU0NrOEM4Z1FJaGpaanpl
            V2VEMEVTcE51bzlwV080YnpDL0xJSHlLdEQwCjByZzYyNnVEdjdjVnBPR2t6Q0Jw
            ZS9sK0FKbHBpT2EwVjJrOFY5N3ZjSjgKLS0tIERrNWlGRmRIZHFpV2JOREJ1aEhk
            WEpvSlB3K1lYVGkzZ3hyc1NyT25MUHMKWo4WmDowebJlGzJsq33OFiX+jnNmzLxV
            oNmn63qUlTC0jdh24+4uI/wK8GSvSDOuGDcgWphyigjLLeiJ0nM5wA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nadt5x4v99usntanplxcmr2rftqkzlh9cd7saffr9ea9zuf9zuxqk0zd7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0V2pRV3Fic2c0Vnhvdklt
            WnA3RHBvUGdPdjJWWXllNE1Kbm9sSDZUd2dRCk1hRnlQMU9yUWZUWUF6aGYvYWZp
            TDNHNXF3c2JkeG9ITmJwNUY1czlwQjgKLS0tIExuS1NqTVpiRGRGS0o1TmYweHMw
            MXhvKy9jcHNLbEorSnFBbzZ4QUZqRk0Kp/HUJ+MtSi7JpR72chkpqH5fmv8uTq2g
            hWMTa4qwCLzKtu7r3VWCC1HbbtUMXsDGtFOPq4slXX3LThHOZQEDDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-18T01:31:44Z"
    mac: ENC[AES256_GCM,data:XtUtuAB9r1QBzOE9C/08CIllrbi5XcB+svqleXe80eWkWPKXMLVATrR7jcHlUZefdT3yYa/eavQ8JORjMj4JwX8s3jQ8ofQPW/urUvtMQM6qCyi836igpXtL0BQm3EES8FyS3LV4ScWGx0QalLwNHafko1ei0XEs1ATSMkvahJ4=,iv:S2/oIx100eJcwQFk5klw9gLyemItfHPNDWHPaZWDIL8=,tag:ucXY+2KX4URYxXwXtlMyBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
